# Generated by Django 2.2.6 on 2019-11-10 16:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='评论')),
                ('star', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='星级')),
                ('reviewtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name_plural': '用户打分及评论',
                'verbose_name': '用户打分及评论',
            },
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='durations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='片长'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='backpost',
            field=models.CharField(blank=True, default='/static/img/m16.jpg', max_length=3000, null=True, verbose_name='详情页海报'),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='picture',
            field=models.CharField(blank=True, default='/static/img/m16.jpg', max_length=1000, null=True, verbose_name='缩略图'),
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='typelist',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='typelist',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='类型'),
        ),
        migrations.DeleteModel(
            name='MovieCategory',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieInfo', verbose_name='电影'),
        ),
    ]
