# Generated by Django 2.2.6 on 2019-11-10 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redate', models.DateField(default=datetime.datetime.now, verbose_name='推荐时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieInfo', verbose_name='电影')),
            ],
            options={
                'verbose_name_plural': '默认电影推荐',
                'verbose_name': '默认电影推荐',
            },
        ),
    ]
